// This file is generated by Slice Machine. Update with care!

import CallToAction from './CallToAction';
import CompanyFeature from './CompanyFeature';
import CustomerLogos from './CustomerLogos';
import CustomerStories from './CustomerStories';
import FaqSection from './FaqSection';
import Feature1 from './Feature1';
import Feature2 from './Feature2';
import Header from './Header';
import HeroSectionBanner from './HeroSectionBanner';
import HeroSlider from './HeroSlider';
import Infra from './Infra';
import Overview from './Overview';
import PriceSection from './PriceSection';
import PriceTable from './PriceTable';
import PrivacyPolicy from './PrivacyPolicy';
import ProductTabs from './ProductTabs';
import PromotionsSection from './PromotionsSection';
import Section1 from './Section1';
import Section2 from './Section2';
import SliderButton from './SliderButton';
import SolutionSection from './SolutionSection';
import SubNavigationItem from './SubNavigationItem';
import ThankYou from './ThankYou';

export {
	CallToAction,
	CompanyFeature,
	CustomerLogos,
	CustomerStories,
	FaqSection,
	Feature1,
	Feature2,
	Header,
	HeroSectionBanner,
	HeroSlider,
	Infra,
	Overview,
	PriceSection,
	PriceTable,
	PrivacyPolicy,
	ProductTabs,
	PromotionsSection,
	Section1,
	Section2,
	SliderButton,
	SolutionSection,
	SubNavigationItem,
	ThankYou,
};

export const components = {
	call_to_action: CallToAction,
	company_feature: CompanyFeature,
	customer_logos: CustomerLogos,
	customer_stories: CustomerStories,
	faq_section: FaqSection,
	feature1: Feature1,
	feature2: Feature2,
	header: Header,
	hero_section_banner: HeroSectionBanner,
	hero_slider: HeroSlider,
	infra: Infra,
	overview: Overview,
	price_section: PriceSection,
	price_table: PriceTable,
	privacy_policy: PrivacyPolicy,
	product_tabs: ProductTabs,
	promotions_section: PromotionsSection,
	section1: Section1,
	section2: Section2,
	slider_button: SliderButton,
	solution_section: SolutionSection,
	sub_navigation_item: SubNavigationItem,
	thank_you: ThankYou,
};
